# Generated by Django 6.0.5 on 2026-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], default='email_verification', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='account_otp_user_id_b04f6b_idx'),
        ),
    ]
